micronaut:
  application:
    name: pixRest

grpc:
  client:
    plaintext: true
    max-retry-attemps: 10
  channels:
    pix:
      address: '${KEY_MANAGER_HOST:localhost}:${KEY_MANAGER_PORT:50051}'
      plaintext: true
      max-retry-attemps: 10

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/pix_rest
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update